### ISSUE TITLE
命令行的三个账号密码换成自己server的账号密码吗？

### ISSUE THREAD

**Issue by BL1ACH** [Shadownc/-Serv00-auto-login#1]
`[  
  { "username": "zhangghao", "password": "mima", "panelnum": "0" },  
  { "username": "zhanghao", "password": "mima", "panelnum": "2" },  
  { "username": "zhanghao", "password": "mima", "panelnum": "3" }  
]`

**Comment by Shadownc** [comment]
你有几个账号就添加几个
[
    {
        "username": "账号",
        "password": "密码",
        "panelnum": "S几就填数字几"
    }
]

**Comment by BL1ACH** [comment]
> 你有几个账号就添加几个 [ { "用户名"："账号"、 "密码"："密码"： "panelnum": "S几就填数字几" } ]

谢谢
